### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by lstruman**

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi @lstruman There were two code matches.  I cleared one as a non-issue, but you do need to add credits to aes_codec.go for two snippets:

- At lines 117 and 194, please insert:

> Copyright 2012 The Go Authors. All rights reserved.
> Licensed under the BSD-3 License

- BSD-3 license needs to be added to top level LICENSE.  Please use from https://opensource.org/license/bsd-3-clause/:

> BSD-3 License
> 
> Copyright <YEAR> <COPYRIGHT HOLDER>
> 
> Redistribution and use in source and binary forms...
> ...
> ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> i.e. don't use an actual YEAR etc., as the specifics are added by NOTICE

and don't use an actual YEAR etc. because the specifics are added in NOTICE

- In top level NOTICE, please add:

> Copyright 2012 The Go Authors. All rights reserved.
> Licensed under the BSD-3 License


Thank you,
Martin Hughes, RDK CMF Compliance Team

**Comment by lstruman** [comment]
@mhughesacn I made changes based on your suggestions, but it still cannot pass the check. If you have a chance, please provide further advice. Thanks.

**Comment by mhughesacn** [comment]
Hi @lstruman Thank you for making the changes.  I have to clear off the matches but the code credits aren't in the right places.  It might be easier to do this:
- Delete lines 135,136 and 214,215 (the new credits).
- Add a single credit after the header (round line 18) to say:

> Some code in Encrypt/Decrypt is:
> Copyright 2012 The Go Authors. All rights reserved.
> Licensed under the BSD-3 License

Thank you.

**Comment by lstruman** [comment]
@mhughesacn I was quite busy recently. I just checked and found all checks passed. Did you help to tweak the check configs? If I asked a colleague to review and approve, then we can proceed to merge?

**Comment by mhughesacn** [comment]
Hi @lstruman - Please see my last comment.  I wanted the credits in a different place but suggested something slightly simpler.  (The checks are still complaining.)
Thank you.

**Review by yotegit — APPROVED** [review]
look good

**Comment by mhughesacn** [comment]
Hi @lstruman : You need one approving reviewer first.  So please ask one of your team to approve.  I don't want to be the approver because my scope is just compliance, not wide enough.
This is how the repository is set up at the moment.  If you want to be able to push without further approval, please report back.

**Review by mhughesacn — APPROVED** [review]

**Comment by mhughesacn** [comment]
Hi @lstruman: I "reviewed" the changes and approved them and now they are good to merge.  Obviously I have no competence to approve except for compliance but your colleague yotegit is presumably good for this.  Please confirm that this is true.  I will check with Steve (rdkcentral admin) to see if yotegit is on the list of approved reviewers.

**Pull request merged**
