### PR TITLE
Add support for Webpa api version in configuration

### PR DESCRIPTION
**Pull request by chaitanyasingla-dt**
The latest WebPA version being used is "v3". There is also a previousApiVersion support in Webpa which allows configuring which apiVersion will be used. 
In the same way, Webpa apiVersion can be added to the WebConfig configuration so that it is compatible with different versions of Webpa.

### CODE REVIEW

**Comment by Sachin4403** [comment]
Hello Team,

The reason for opening this PR, we should have the support of changing the Tr1d1um API versions from config.

As of today, Tr1d1um is migrated to V3, but in the webconfig codebase still, we are referring to tr1d1um V2 API, and the V2 API of Tr1d1um will be working only and only if you had enabled the `previousVersionSupport` else all the time this API will be failing and CPE won't be notified about the changes which are there in webconfig, and these changes won't be pulled by the CPE.

**Review by lstruman — APPROVED** [review]

**Comment by Sachin4403** [comment]
Hello @lstruman  Can we merge this PR?

**Comment by Sachin4403** [comment]
Hi @vpooja820 

Do we have any blocker for merging this PR?

**Comment by chaitanyasingla-dt** [comment]
This code functionality is already present in develop branch so it is not required now.
Closing the PR.

**Pull request closed without merging**
